module.exports = {
  ToursService: require('./tours'),
  UsersService: require('./users'),
  RolesService: require('./roles'),
  TokensService: require('./token'),
  HotelsService: require('./hotels'),
  PaymentsService: require('./payments'),
  HotelImagesService: require('./hotel-images'),
  TourDetailsService: require('./tour-details'),
  TourBookingsService: require('./tour-bookings'),
  TourRequestsService: require('./tour-requests'),
  TourSchedulesService: require('./tour-schedules'),
  TourCategoriesService: require('./tour-categories'),
  PaymentMethodsService: require('./payment-methods'),
  TourTransportsService: require('./tour-transports'),
  TourParticipantsService: require('./tour-participants'),
  TourDestinationsService: require('./tour-destinations'),
  TourDetailImagesService: require('./tour-detail-images'),
};
