module.exports = {
  UsersModel: require('./user'),
  ToursModel: require('./tour'),
  RolesModel: require('./role'),
  ToursModel: require('./tour'),
  HotelsModel: require('./hotel'),
  TokensModel: require('./token'),
  HotelImagesModel: require('./hotel-image'),
  TourDetailsModel: require('./tour-detail'),
  TourSchedulesModel: require('./tour-schedule'),
  TourCategoriesModel: require('./tour-category'),
  TourTransportsModel: require('./tour-transport'),
  TourParticipantsModel: require('./tour-participant'),
  TourDestinationsModel: require('./tour-destination'),
  TourDetailImagesModel: require('./tour-detail-image'),
};
