module.exports = {
  UsersModel: require('./user'),
  ToursModel: require('./tour'),
  RolesModel: require('./role'),
  ToursModel: require('./tour'),
  HotelsModel: require('./hotel'),
  TokensModel: require('./token'),
  PaymentsModel: require('./payment'),
  HotelImagesModel: require('./hotel-image'),
  TourDetailsModel: require('./tour-detail'),
  TourBookingsModel: require('./tour-booking'),
  TourSchedulesModel: require('./tour-schedule'),
  TourCategoriesModel: require('./tour-category'),
  PaymentMethodsModel: require('./payment-method'),
  TourTransportsModel: require('./tour-transport'),
  TourParticipantsModel: require('./tour-participant'),
  TourDestinationsModel: require('./tour-destination'),
  TourRequirementsModel: require('./tour-requirement'),
  TourDetailImagesModel: require('./tour-detail-image'),
};
